# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O_tBvjOxYD0LiXHYHwzCMTLPkAOANh06
"""

import matplotlib.pyplot as plt
import numpy as np

Mediciones = np.array([5.0291, 6.5099, 5.3666, 4.1272, 4.2948, 6.1261, 10.0502, 9.1614, 7.5677,
7.2920, 10.0357, 11.0708, 13.4045, 12.8415, 11.9666, 11.0765, 11.7774, 14.5701, 17.0440,
17.0398, 15.9069, 15.4850, 15.5112, 17.6572])
x1 = 3.1535984659895244
x2 = 0.58690874813928107
x3  = 1.9733212501262221

def Ajuste(x):
 y_apr = x1 + (x2*x) + x3*np.sin(x)
 return y_apr

x_1 = np.linspace(1,25,10000)
x_2 = np.array([1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
    19, 20, 21, 22, 23, 24, 25])

plt.figure(figsize=(8,8))
plt.plot(x_1, Ajuste(x_1), label='Ajuste', color='orange')
plt.scatter(x_2, Mediciones, label='Mediciones')
plt.legend()
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

Mediciones = np.array([5.0291, 6.5099, 5.3666, 4.1272, 4.2948, 6.1261, 10.0502, 9.1614, 7.5677,
7.2920, 10.0357, 11.0708, 13.4045, 12.8415, 11.9666, 11.0765, 11.7774, 14.5701, 17.0440,
17.0398, 15.9069, 15.4850, 15.5112, 17.6572])


def Ajuste(x):
 y_apr = 3.2897357826317326 + (0.60620799226710897*x) + 1.2952760853789362*np.sin(x)
 return y_apr

x_1 = np.linspace(1,25)
x_2 = np.arange(1, len(Mediciones) + 1)

plt.figure(figsize=(8,8))
plt.plot(x_1, Ajuste(x_1), label='Ajuste', color='orange')
plt.scatter(x_2, Mediciones, label='Mediciones')
plt.legend()
plt.grid(True)
plt.show()